### ISSUE TITLE
src/Attributes.js has typo in 'use strict' on line 1

### ISSUE THREAD

**Issue by gesslar** [lnguyenfx/simplemud#1]
It says `'use trict'` when it should say `'use strict'`.

Tried to push a patch, but it wouldn't let me. :(

**Comment by lnguyenfx** [comment]
Thanks for the report. Have you tried forking this repository, apply your patch, and then submit a pull request?

More details on how to do this can be found here:
https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

If done properly, your fix should be integrated in this repository once the pull request is approved. Thanks.

**Comment by gesslar** [comment]
I will give that a shot! Thank you!

**Comment by gesslar** [comment]
#2 submitted
